### ISSUE TITLE
Use custom commit hash of `spore-contract` as parameter for `prepare.sh`

### ISSUE THREAD

**Issue by ashuralyk** [Dawn-githup/spore_devenv#1]
# Description

I plan to integration this devnet tool into `spore-contract` when committing the PR, but the branch in `prepare.sh` is always the `master`, so I recommend adding commit parameter for this `prepare.sh` to checkout specific commit.

If no commit hash provided, `master` is default option.

**Comment by Dawn-githup** [comment]
- Repair branch:
https://github.com/Dawn-githup/spore_devenv/commit/74f5d4b40d787c943e858109b7dd3fcbfb5aec65

- Reference instructions for use:
https://github.com/Dawn-githup/spore_devenv/blob/main/README.md

@ashuralyk Could you please check and see if any optimization adjustments are needed?

**Comment by ashuralyk** [comment]
> * Repair branch:
>   [74f5d4b](https://github.com/Dawn-githup/spore_devenv/commit/74f5d4b40d787c943e858109b7dd3fcbfb5aec65)
> * Reference instructions for use:
>   https://github.com/Dawn-githup/spore_devenv/blob/main/README.md
> 
> @ashuralyk Could you please check and see if any optimization adjustments are needed?

LGTM, please update it ASAP @Dawn-githup
